Cypress.on('uncaught:exception',(err, runnable)=>{
  return false;
})

import { faker } from '@faker-js/faker';


describe('Do it', () => {
  it('logines', () => {
    cy.visit('https://test.admin.delever.uz/#/auth/login')
    cy.get('.p-6 > :nth-child(1) > .flex').type("oybek3")
    cy.get('.p-6 > :nth-child(2) > .items-center').type("oybek1024")
    cy.get('.button').click()
    cy.wait(2000)
    cy.get(':nth-child(3) > a.flex > .active-sidebar').click()
    cy.get('.h-14.justify-between').find("button").first().click()
    cy.get('#first_name').type("Test Name")
    cy.get('#last_name').type("Test Surename")
    cy.get('#phone').type(faker.phone.number('90#######'))
    cy.get('.select__control').click()
    cy.get(".select__menu").find("div").first().click()
    cy.get(':nth-child(2) > .button').click()
  })
  it('logines', () => {
    cy.visit('https://test.admin.delever.uz/#/auth/login')
    cy.get('.p-6 > :nth-child(1) > .flex').type("oybek3")
    cy.get('.p-6 > :nth-child(2) > .items-center').type("oybek1024")
    cy.get('.button').click()
    cy.wait(2000)
    cy.get(':nth-child(3) > a.flex > .active-sidebar').click()
    cy.get('.h-14.justify-between').find("button").first().click()
    cy.get('#first_name').type("Test Name")
    cy.get('#last_name').type("Test Surename")
    cy.get('#phone').type(faker.phone.number('90#######'))
    cy.get('.select__control').click()
    cy.get(".select__menu").find("div").first().click()
    cy.get(':nth-child(2) > .button').click()
  })
  it('logines', () => {
    cy.visit('https://test.admin.delever.uz/#/auth/login')
    cy.get('.p-6 > :nth-child(1) > .flex').type("oybek3")
    cy.get('.p-6 > :nth-child(2) > .items-center').type("oybek1024")
    cy.get('.button').click()
    cy.wait(2000)
    cy.get(':nth-child(3) > a.flex > .active-sidebar').click()
    cy.get('.h-14.justify-between').find("button").first().click()
    cy.get('#first_name').type("Test Name")
    cy.get('#last_name').type("Test Surename")
    cy.get('#phone').type(faker.phone.number('90#######'))
    cy.get('.select__control').click()
    cy.get(".select__menu").find("div").first().click()
    cy.get(':nth-child(2) > .button').click()
  })
  it('logines', () => {
    cy.visit('https://test.admin.delever.uz/#/auth/login')
    cy.get('.p-6 > :nth-child(1) > .flex').type("oybek3")
    cy.get('.p-6 > :nth-child(2) > .items-center').type("oybek1024")
    cy.get('.button').click()
    cy.wait(2000)
    cy.get(':nth-child(3) > a.flex > .active-sidebar').click()
    cy.get('.h-14.justify-between').find("button").first().click()
    cy.get('#first_name').type("Test Name")
    cy.get('#last_name').type("Test Surename")
    cy.get('#phone').type(faker.phone.number('90#######'))
    cy.get('.select__control').click()
    cy.get(".select__menu").find("div").first().click()
    cy.get(':nth-child(2) > .button').click()
  })
  it('logines', () => {
    cy.visit('https://test.admin.delever.uz/#/auth/login')
    cy.get('.p-6 > :nth-child(1) > .flex').type("oybek3")
    cy.get('.p-6 > :nth-child(2) > .items-center').type("oybek1024")
    cy.get('.button').click()
    cy.wait(2000)
    cy.get(':nth-child(3) > a.flex > .active-sidebar').click()
    cy.get('.h-14.justify-between').find("button").first().click()
    cy.get('#first_name').type("Test Name")
    cy.get('#last_name').type("Test Surename")
    cy.get('#phone').type(faker.phone.number('90#######'))
    cy.get('.select__control').click()
    cy.get(".select__menu").find("div").first().click()
    cy.get(':nth-child(2) > .button').click()
  })
})